trigger:
- main

variables:
- group: credentials
- name: dockerhub-user
  value: 'gadzina13'
- name: image_name
  value: 'gad_docker_test'
- name: tag
  value: 'latest'
- name: dockerImage
  value: $(dockerhub-user)/$(image_name):$(tag)


jobs:
- job: RunOnAgents
  strategy:
    matrix:
      gad-mini-pc2:
        agentName: gad-mini-pc2
      gad-agent-pi4b:
        agentName: gad-agent-pi4b

  
  pool:
    name: gads-agent-pool
    demands:
    - agent.name -equals $(agentName)

  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Azure dla studentów(232fe18a-7562-4ae5-9507-29d2bde01130)'
      KeyVaultName: 'credentialsforproject'
      SecretsFilter: '*'
      RunAsPreJob: true

  - script: docker login -u $(dockerhub-username) -p $(dockerhub-password)
    displayName: 'Login to Docker Hub'


  - script: docker build --build-arg BUILD_AGENT=$(Agent.Name) -t $(dockerhub-user)/$(image_name):$(tag) .
    displayName: 'Build and Tag Docker Image'

  - script: docker push $(dockerImage)
    displayName: 'Push Docker Image to Docker Hub'

  - script: docker rmi $(dockerImage)
    displayName: 'Remove local Docker image'

  - script: docker pull $(dockerImage)
    displayName: 'Pull Docker Image from Docker Hub'

  - script: docker run --name gad_test_container $(dockerImage)
    displayName: 'Run Docker Image'

  - script: docker rm gad_test_container
    displayName: 'Remove Docker container after execution'

  - script: docker rmi $(dockerImage)
    displayName: 'Remove Docker image after testing'

  - script: |
      echo Original: $(Build.Repository.Uri)
      NEW_REPO_URI=$(echo $(Build.Repository.Uri) | sed 's/https:\/\/.*@/https:\/\//')
      echo Modified: $NEW_REPO_URI
      echo "##vso[task.setvariable variable=NEW_REPO_URI]$NEW_REPO_URI"
    displayName: 'Modify Build Repository URI (Linux)'
    condition: eq(variables['Agent.OS'], 'Linux')

  - powershell: |
      $originalUri = "$(Build.Repository.Uri)"
      Write-Host "Original: $originalUri"
      $modifiedUri = $originalUri -replace "https://.*@", "https://"
      Write-Host "Modified: $modifiedUri"
      echo "##vso[task.setvariable variable=NEW_REPO_URI]$modifiedUri"
    displayName: 'Modify Build Repository URI (Windows)'
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - task: mirror-git-repository-vsts-task@1
    inputs:
      sourceGitRepositoryUri: '$(NEW_REPO_URI)'
      sourceGitRepositoryPersonalAccessToken: '$(azure_pat)'
      destinationGitRepositoryUri: 'https://github.com/jakmrowka/azure-docker-test'
      destinationGitRepositoryPersonalAccessToken: '$(git_pat)'

